const rawSchedule = [
    "11-Jun|México|Sudáfrica", "11-Jun|Corea|Rep. Checa", "12-Jun|Canadá|Bosnia", "12-Jun|USA|Paraguay",
    "13-Jun|Haití|Escocia", "13-Jun|Australia|Turquía", "13-Jun|Brasil|Marruecos", "13-Jun|Qatar|Suiza",
    "14-Jun|Costa de Marfil|Ecuador", "14-Jun|Alemania|Curazao", "14-Jun|Países Bajos|Japón", "14-Jun|Suecia|Túnez",
    "15-Jun|Arabia S.|Uruguay", "15-Jun|España|Cabo Verde", "15-Jun|Irán|N. Zelanda", "15-Jun|Bélgica|Egipto",
    "16-Jun|Francia|Senegal", "16-Jun|Irak|Noruega", "16-Jun|Argentina|Argelia", "16-Jun|Austria|Jordania",
    "17-Jun|Ghana|Panamá", "17-Jun|Inglaterra|Croacia", "17-Jun|Portugal|RD Congo", "17-Jun|Uzbekistán|Colombia",
    "18-Jun|Rep. Checa|Sudáfrica", "18-Jun|Suiza|Bosnia", "18-Jun|Canadá|Qatar", "18-Jun|México|Corea",
    "19-Jun|Brasil|Haití", "19-Jun|Escocia|Marruecos", "19-Jun|Turquía|Paraguay", "19-Jun|USA|Australia",
    "20-Jun|Alemania|Costa de Marfil", "20-Jun|Ecuador|Curazao", "20-Jun|Países Bajos|Suecia", "20-Jun|Túnez|Japón",
    "21-Jun|Uruguay|Cabo Verde", "21-Jun|España|Arabia S.", "21-Jun|Bélgica|Irán", "21-Jun|N. Zelanda|Egipto",
    "22-Jun|Noruega|Senegal", "22-Jun|Francia|Irak", "22-Jun|Argentina|Austria", "22-Jun|Jordania|Argelia",
    "23-Jun|Inglaterra|Ghana", "23-Jun|Panamá|Croacia", "23-Jun|Portugal|Uzbekistán", "23-Jun|Colombia|RD Congo",
    "24-Jun|Escocia|Brasil", "24-Jun|Marruecos|Haití", "24-Jun|Suiza|Canadá", "24-Jun|Bosnia|Qatar",
    "24-Jun|Rep. Checa|México", "24-Jun|Sudáfrica|Corea", "25-Jun|Curazao|Costa de Marfil",
    "25-Jun|Ecuador|Alemania", "25-Jun|Japón|Suecia", "25-Jun|Túnez|Países Bajos", "25-Jun|Turquía|USA",
    "25-Jun|Paraguay|Australia", "26-Jun|Noruega|Francia", "26-Jun|Senegal|Irak", "26-Jun|Egipto|Irán",
    "26-Jun|N. Zelanda|Bélgica", "26-Jun|Cabo Verde|Arabia S.", "26-Jun|Uruguay|España", "27-Jun|Panamá|Inglaterra",
    "27-Jun|Croacia|Ghana", "27-Jun|Argelia|Austria", "27-Jun|Jordania|Argentina", "27-Jun|Colombia|Portugal",
    "27-Jun|RD Congo|Uzbekistán"
];